### ISSUE TITLE
add play again / quit button to winner modal

### ISSUE THREAD

**Issue by jfetter** [rachelrobynslater/CAH#14]
- there is a SWAL modal that comes up when you win... but we need to add buttons and ng click even that has an sref to go to profile page if quit clicked and an ng click that triggers player to log out and screen to reload --or something if play again is clicked.

**Comment by rachelrobynslater** [comment]
The 'win' state SWAL was added to gameMaster.js - containing function based on 'IsConfirm' to allow users to 'play again' (refresh & clear out game) vs. 'send back to user profile'.
